name: .NET Core

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: GunplaOnlineShop
      run: dotnet restore
    - name: Build
      working-directory: GunplaOnlineShop
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: GunplaOnlineShop
      run: dotnet test --no-restore --verbosity normal
